// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVmk3F9lc2eO84L2tB-B9wDqQuEjwVTg8',
    appId: '1:1085513790662:web:26b2bac52fb4b885e553c7',
    messagingSenderId: '1085513790662',
    projectId: 'studentsaccomodations-27ae2',
    authDomain: 'studentsaccomodations-27ae2.firebaseapp.com',
    storageBucket: 'studentsaccomodations-27ae2.firebasestorage.app',
    measurementId: 'G-RXES87MNCN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIvuxAa5-VfysJCnIrcR6eLvgC3JyesI',
    appId: '1:556304789736:ios:18d700c0003821ea19995d',
    messagingSenderId: '556304789736',
    projectId: 'e-commerce-2aba7',
    storageBucket: 'e-commerce-2aba7.firebasestorage.app',
    iosBundleId: 'com.example.studentsaccomodations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIvuxAa5-VfysJCnIrcR6eLvgC3JyesI',
    appId: '1:556304789736:ios:18d700c0003821ea19995d',
    messagingSenderId: '556304789736',
    projectId: 'e-commerce-2aba7',
    storageBucket: 'e-commerce-2aba7.firebasestorage.app',
    iosBundleId: 'com.example.studentsaccomodations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGPw2mSAjpb43X1LEVaj64Yq12VH4XUFU',
    appId: '1:556304789736:web:6eb5ff20e3fbc94719995d',
    messagingSenderId: '556304789736',
    projectId: 'e-commerce-2aba7',
    authDomain: 'e-commerce-2aba7.firebaseapp.com',
    storageBucket: 'e-commerce-2aba7.firebasestorage.app',
    measurementId: 'G-5CR00B4XHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34ESS5XSM4jnJ9JFIagBizc5Fo_pv5ic',
    appId: '1:1085513790662:android:dd0918461634f03de553c7',
    messagingSenderId: '1085513790662',
    projectId: 'studentsaccomodations-27ae2',
    storageBucket: 'studentsaccomodations-27ae2.firebasestorage.app',
  );

}